### ISSUE TITLE
Application crashing when running for a substantial amount of time

### ISSUE THREAD

**Issue by c-sig** [nzbasic/batch-beatmap-downloader#2]
Environment: Windows 10 IoT Enterprise LTSC 21H2 Build No. 19044.1586

Been running into some issues where the downloader straight up stops responding (though it still downloads as the download count still goes up in these instances) when downloading a huge batch like the entirety of the Ranked section. Sometimes throws an error regarding rendering or something though I'll just include it in a comment as it only happens once in a while. I also believe the app to be the cause of multiple software issues such as it forcing other programs to crash by a huge CPU usage spike though this is just speculation (everything seems to work fine when app isn't running)

Steps to reproduce:
- Select Ranked Map Status in the query builder
- Search and download
- Wait half an hour to two hours
- Profit

**Comment by nzbasic** [comment]
I think this is due to too many messages being sent between the renderer and main process for showing the current beatmap download percentage, if the renderer can't handle the messages they just build up over time and slow the program down 

Fixing in next release (today)
