### ISSUE TITLE
Downloading .osz files with nothing in them

### ISSUE THREAD

**Issue by c-sig** [nzbasic/batch-beatmap-downloader#5]
There are 1582 .osz files which contain no beatmap files, maybe some files got corrupted due to storage malfunctions? (not sure tbh).

v1.0.8
Tried redownloading as well, doesn't work as of 03/18/2022.

**Comment by nzbasic** [comment]
This is very odd, the files seem fine on the server side, I will investigate, thank you for reporting

**Comment by nzbasic** [comment]
Found the issue, I saved the file size of each map beforehand, but this must have failed and set some of the file sizes to 0. I changed the code to calculate the file size each time and the files are serving properly now
