### ISSUE TITLE
download stuck at 96% for hours

### ISSUE THREAD

**Issue by loweare** [nzbasic/batch-beatmap-downloader#6]
![image](https://user-images.githubusercontent.com/53896107/161735946-af14b17f-83ff-4e6a-a12b-cc0df855dddd.png)
it has been like this for hours and it seems like I cannot do anything about it

**Comment by nzbasic** [comment]
One file failed to download for some reason (can happen randomly) but the app wasn't adding the file size to the progress bar.
So this download is actually complete, I have pushed a new update which should stop this from happening
